-- Phase 1: LKB Complete Migration - Corrected columns
-- Insert additional legal instruments to reach 120+ using correct columns

INSERT INTO public.legal_instruments (instrument_uid, title, short_title, abbreviation, jurisdiction, instrument_type, current_status, domain_tags, authority) VALUES
  -- Federal Laws
  ('sr-101', 'Constitution fédérale de la Confédération suisse', 'Constitution fédérale', 'Cst.', 'CH', 'constitution', 'in_force', ARRAY['CONSTITUTION'], 'Assemblée fédérale'),
  ('sr-210', 'Code civil suisse', 'Code civil', 'CC', 'CH', 'loi', 'in_force', ARRAY['PROTECTION', 'SOCIAL'], 'Assemblée fédérale'),
  ('sr-220', 'Code des obligations', 'Code des obligations', 'CO', 'CH', 'loi', 'in_force', ARRAY['ECONOMIE'], 'Assemblée fédérale'),
  ('sr-311', 'Code pénal suisse', 'Code pénal', 'CP', 'CH', 'loi', 'in_force', ARRAY['JUSTICE'], 'Assemblée fédérale'),
  ('sr-272', 'Code de procédure civile', 'CPC', 'CPC', 'CH', 'loi', 'in_force', ARRAY['JUSTICE'], 'Assemblée fédérale'),
  ('sr-312', 'Code de procédure pénale suisse', 'CPP', 'CPP', 'CH', 'loi', 'in_force', ARRAY['JUSTICE'], 'Assemblée fédérale'),
  ('sr-832.10', 'Loi fédérale sur l''assurance-maladie', 'LAMal', 'LAMal', 'CH', 'loi', 'in_force', ARRAY['SANTE'], 'Assemblée fédérale'),
  ('sr-831.10', 'Loi fédérale sur l''assurance-vieillesse et survivants', 'LAVS', 'LAVS', 'CH', 'loi', 'in_force', ARRAY['SOCIAL'], 'Assemblée fédérale'),
  ('sr-831.20', 'Loi fédérale sur l''assurance-invalidité', 'LAI', 'LAI', 'CH', 'loi', 'in_force', ARRAY['SOCIAL'], 'Assemblée fédérale'),
  ('sr-235.1', 'Loi fédérale sur la protection des données', 'LPD', 'LPD', 'CH', 'loi', 'in_force', ARRAY['PROTECTION', 'JUSTICE'], 'Assemblée fédérale'),
  ('sr-312.5', 'Loi fédérale sur l''aide aux victimes d''infractions', 'LAVI', 'LAVI', 'CH', 'loi', 'in_force', ARRAY['JUSTICE', 'SOCIAL'], 'Assemblée fédérale'),
  ('sr-412.10', 'Loi fédérale sur la formation professionnelle', 'LFPr', 'LFPr', 'CH', 'loi', 'in_force', ARRAY['EDUCATION'], 'Assemblée fédérale'),
  ('sr-142.20', 'Loi fédérale sur les étrangers et l''intégration', 'LEI', 'LEI', 'CH', 'loi', 'in_force', ARRAY['SOCIAL'], 'Assemblée fédérale'),
  ('sr-173.110', 'Loi sur le Tribunal fédéral', 'LTF', 'LTF', 'CH', 'loi', 'in_force', ARRAY['JUSTICE'], 'Assemblée fédérale'),
  ('sr-700', 'Loi fédérale sur l''aménagement du territoire', 'LAT', 'LAT', 'CH', 'loi', 'in_force', ARRAY['TERRITOIRE'], 'Assemblée fédérale'),
  ('sr-814.01', 'Loi fédérale sur la protection de l''environnement', 'LPE', 'LPE', 'CH', 'loi', 'in_force', ARRAY['TERRITOIRE'], 'Assemblée fédérale'),
  ('sr-641.20', 'Loi fédérale sur la taxe sur la valeur ajoutée', 'LTVA', 'LTVA', 'CH', 'loi', 'in_force', ARRAY['FINANCES'], 'Assemblée fédérale'),
  ('sr-830.1', 'Loi fédérale sur la partie générale des assurances sociales', 'LPGA', 'LPGA', 'CH', 'loi', 'in_force', ARRAY['SOCIAL'], 'Assemblée fédérale'),
  
  -- Vaud Laws
  ('rsv-400.01', 'Constitution du Canton de Vaud', 'Constitution VD', 'Cst-VD', 'VD', 'constitution', 'in_force', ARRAY['CONSTITUTION'], 'Grand Conseil'),
  ('rsv-173.11', 'Loi sur la juridiction administrative', 'LJPA', 'LJPA', 'VD', 'loi', 'in_force', ARRAY['JUSTICE'], 'Grand Conseil'),
  ('rsv-550.11', 'Loi sur les impôts directs cantonaux', 'LI', 'LI', 'VD', 'loi', 'in_force', ARRAY['FINANCES'], 'Grand Conseil'),
  ('rsv-650.11', 'Loi sur les impôts communaux', 'LICom', 'LICom', 'VD', 'loi', 'in_force', ARRAY['FINANCES'], 'Grand Conseil'),
  ('rsv-180.11', 'Loi sur la police cantonale', 'LPol', 'LPol', 'VD', 'loi', 'in_force', ARRAY['JUSTICE'], 'Grand Conseil'),
  ('rsv-411.01', 'Loi sur l''enseignement obligatoire', 'LEO', 'LEO', 'VD', 'loi', 'in_force', ARRAY['EDUCATION'], 'Grand Conseil'),
  ('rsv-411.01.1', 'Règlement d''application LEO', 'RLEO', 'RLEO', 'VD', 'reglement', 'in_force', ARRAY['EDUCATION'], 'Conseil d''État'),
  ('rsv-416.11', 'Loi sur l''enseignement secondaire supérieur', 'LESS', 'LESS', 'VD', 'loi', 'in_force', ARRAY['EDUCATION'], 'Grand Conseil'),
  ('rsv-419.11', 'Loi sur la formation professionnelle VD', 'LVFPr', 'LVFPr', 'VD', 'loi', 'in_force', ARRAY['EDUCATION'], 'Grand Conseil'),
  ('rsv-850.11', 'Loi sur l''action sociale vaudoise', 'LASV', 'LASV', 'VD', 'loi', 'in_force', ARRAY['SOCIAL'], 'Grand Conseil'),
  ('rsv-850.41', 'Loi sur l''accueil de jour des enfants', 'LAJE', 'LAJE', 'VD', 'loi', 'in_force', ARRAY['SOCIAL'], 'Grand Conseil'),
  ('rsv-850.31', 'Loi sur la protection des mineurs', 'LProMin', 'LProMin', 'VD', 'loi', 'in_force', ARRAY['SOCIAL', 'PROTECTION'], 'Grand Conseil'),
  ('rsv-211.251', 'Loi d''application du droit fédéral de la protection de l''adulte', 'LVPAE', 'LVPAE', 'VD', 'loi', 'in_force', ARRAY['PROTECTION'], 'Grand Conseil'),
  ('rsv-800.01', 'Loi sur la santé publique', 'LSP', 'LSP', 'VD', 'loi', 'in_force', ARRAY['SANTE'], 'Grand Conseil'),
  ('rsv-810.01', 'Loi sur les établissements sanitaires', 'LES', 'LES', 'VD', 'loi', 'in_force', ARRAY['SANTE'], 'Grand Conseil'),
  ('rsv-700.11', 'Loi sur l''aménagement du territoire et les constructions', 'LATC', 'LATC', 'VD', 'loi', 'in_force', ARRAY['TERRITOIRE'], 'Grand Conseil'),
  ('rsv-700.11.1', 'Règlement d''application de la LATC', 'RLATC', 'RLATC', 'VD', 'reglement', 'in_force', ARRAY['TERRITOIRE'], 'Conseil d''État'),
  ('rsv-730.01', 'Loi sur l''énergie', 'LVLEne', 'LVLEne', 'VD', 'loi', 'in_force', ARRAY['TERRITOIRE'], 'Grand Conseil'),
  ('rsv-740.01', 'Loi sur les routes', 'LRou', 'LRou', 'VD', 'loi', 'in_force', ARRAY['TRANSPORTS'], 'Grand Conseil'),
  ('rsv-741.01', 'Loi sur la mobilité et les transports publics', 'LMTP', 'LMTP', 'VD', 'loi', 'in_force', ARRAY['TRANSPORTS'], 'Grand Conseil'),
  ('rsv-900.01', 'Loi sur l''appui au développement économique', 'LADE', 'LADE', 'VD', 'loi', 'in_force', ARRAY['ECONOMIE'], 'Grand Conseil'),
  ('rsv-172.31', 'Loi sur le personnel de l''État de Vaud', 'LPers-VD', 'LPers-VD', 'VD', 'loi', 'in_force', ARRAY['INSTITUTIONS'], 'Grand Conseil'),
  ('rsv-432.01', 'Loi sur la protection des données personnelles', 'LPrD', 'LPrD', 'VD', 'loi', 'in_force', ARRAY['PROTECTION', 'JUSTICE'], 'Grand Conseil'),
  ('rsv-312.01', 'Loi d''exécution du CPC', 'LECPC', 'LECPC', 'VD', 'loi', 'in_force', ARRAY['JUSTICE'], 'Grand Conseil'),
  ('rsv-312.11', 'Loi d''exécution du CPP', 'LECPP', 'LECPP', 'VD', 'loi', 'in_force', ARRAY['JUSTICE'], 'Grand Conseil'),
  ('rsv-450.11', 'Loi sur le patrimoine mobilier et immatériel', 'LPMI', 'LPMI', 'VD', 'loi', 'in_force', ARRAY['CULTURE'], 'Grand Conseil'),
  ('rsv-400.11', 'Loi sur l''organisation du Conseil d''État', 'LOCE', 'LOCE', 'VD', 'loi', 'in_force', ARRAY['INSTITUTIONS'], 'Grand Conseil'),
  ('rsv-810.02', 'Loi sur les EMS', 'LEMS', 'LEMS', 'VD', 'loi', 'in_force', ARRAY['SANTE'], 'Grand Conseil'),
  ('rsv-415.01', 'Loi sur l''Université de Lausanne', 'LUL', 'LUL', 'VD', 'loi', 'in_force', ARRAY['EDUCATION'], 'Grand Conseil'),
  ('rsv-419.01', 'Loi sur les hautes écoles vaudoises', 'LHEV', 'LHEV', 'VD', 'loi', 'in_force', ARRAY['EDUCATION'], 'Grand Conseil'),
  ('rsv-175.11', 'Loi sur les communes', 'LC', 'LC', 'VD', 'loi', 'in_force', ARRAY['INSTITUTIONS'], 'Grand Conseil'),
  ('rsv-850.51', 'Loi sur les prestations complémentaires familles', 'LPCFam', 'LPCFam', 'VD', 'loi', 'in_force', ARRAY['SOCIAL'], 'Grand Conseil'),
  ('rsv-181.11', 'Loi pénale vaudoise', 'LPén', 'LPén', 'VD', 'loi', 'in_force', ARRAY['JUSTICE'], 'Grand Conseil')
ON CONFLICT (instrument_uid) DO UPDATE SET
  title = EXCLUDED.title,
  abbreviation = EXCLUDED.abbreviation,
  current_status = EXCLUDED.current_status,
  domain_tags = EXCLUDED.domain_tags;